{{- if .Values.usageApi.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: usage-api
  labels:
    app.kubernetes.io/name: usage-api
    {{- include "telecom-app.labels" . | nindent 4 }}
  {{- with .Values.usageApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.notificationService.enabled }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    {{- include "telecom-app.labels" . | nindent 4 }}
  {{- with .Values.notificationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
