{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- range $name, $enabled := dict "usage-api" .Values.usageApi.enabled "notification-service" .Values.notificationService.enabled }}
{{- if $enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "telecom-app.labels" $ | nindent 4 }}
    {{- with $.Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.monitoring.serviceMonitor.interval }}
{{- end }}
{{- end }}
{{- end }}
